[project]
name = "tack"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "rhino-python-renderer",
    "run-in-rhino",
]

[tool.uv.sources]
rhino-python-renderer = { path = "../rhino-python-renderer", editable = true }
run-in-rhino = { path = "../run-in-rhino", editable = true }
