STATE_KEY = "GlueObjects.State"
HANDLER_KEY = "GlueObjects.Handler"
AFTER_HANDLER_KEY = "GlueObjects.AfterHandler"
REPLACE_HANDLER_KEY = "GlueObjects.ReplaceHandler"
IDLE_HANDLER_KEY = "GlueObjects.IdleHandler"
PENDING_REPLACEMENTS_KEY = "GlueObjects.PendingReplacements"
CONDUIT_KEY = "GlueObjects.Conduit"
